language: node_js
node_js:
  - '6.10.0'
addons:
  apt:
    packages:
    - sshpass
before_script:
  - npm install -g yarn
  - yarn
script:
  - npm test
after_success:
  - sshpass -p "$PWD" scp -r $USER@$DOMAIN:$FOLDER_PATH *
branches:
  only:
    - master